### ISSUE TITLE
ADC1 access?

### ISSUE THREAD

**Issue by timhavens** [IW0HDV/extio-iw0hdv#1]
Would it be possible to add the ability to access the ADC1 for HF direct?  I've read recently that someone created an experimental driver for this ability in SDR# with their DLL for Airspy.  I need a DLL for HDSDR that can do this tho.

Ideas?  Comments?

de NW0W

**Comment by timhavens** [comment]
Youssef writes:

"There's an experimental firmware that streams 20MSPS out of ADC 1:
http://airspy.com/downloads/airspy_ddc.zip
I also included a dll for sdr# to do the frequency translation and decimation.
To flash the firmware, replace airspy_rom_to_tam.bin and follow the instructions in this page:
https://github.com/airspy/firmware/releases
To get back to the old firmware flash the original release."

---

I asked him about use with HDSDR and his comments are here: http://airspy.com/index.php/forums/topic/adc1-extio-dll-for-hdsdr/

"Just use the special firmware with the standard extio and see what happens."

---

I tried that and it appears that either the extio-iw0hdv will not accept a freq. in the low HF range via HDSDR or something in HDSDR is restricting it.  I suspect however, that this would be something in your EXTIO.

Please consider this 'feature request' at some point, or advise if I'm just doing something wrong.

**Comment by timhavens** [comment]
I tested the use of the firmware which supports ADC1 today along with HDSDR.  This works quite good as long as I use "SDR hardware connected to antenna".  

However, I'm trying to use this via the 9MHz output of an FTDX-5000 and I need to use "SDR on IF output, which is controlled by - OmniRig".  When I attempt to do so with an IF-FREQ of 9,000,000 (9000000) Hz I get a message which states "ExtIO-DLL don't accept IF-Frequency".  

So I imaging that this is a restriction in the ExtIO DLL itself that's stopped me.

Help would be appreciated.

**Comment by amontefusco** [comment]
The freq limitation is there

https://github.com/amontefusco/extio-iw0hdv/blob/master/airspy/extio_airspy.cpp, line 134

```
int ExtIODll::SetHWLO(long freq)
{
/* Parameter freq shall be between 24000000(24MHz) and 1750000000(1.75GHz) */
    if (freq < 24000000) return -10000;
    if (freq > 1750000000) return 1750000000;

    if (pExr) pExr->set_frequency (freq);

    return 0;
}
```

It derived from shared library (and I guess, from the firmware), at least at the time I wrote my code. Just comment out the two if's and recompile.

**Comment by timhavens** [comment]
Thanks for the reply:

http://airspy.com/downloads/airspy_ddc.zip _firmware_ allows tuning below 24 Mhz and uses the ADC1 of the airspy for samples.  

Any chance you could add an option for this in your DLL?  Or build a version of the DLL as an experimental version and make it available?

Thank you for your consideration.

**Comment by amontefusco** [comment]
Tim,
you have a private email with the pointer where an experimental release is found.
Look to the gui, I added a check box, unticking it any frequency boundary check is relaxed and you can force anything the hardware manages.

**Comment by timhavens** [comment]
FYI this is working PERFECTLY!  

I just needed to add a LNA and a bandpass filter to keep the signals clean.

Took a little bit to get HDSDR IF-Frequency and Global Offset set up, but only took about 20 minutes to flash the Airspy with it's required firmware, replace the EXTIO with this experimental on, find some known strong signals, and calibrate HDSDR.  

Seems to be working very well.

My primary radio is a Yaesu FTDX-5000 connected to the 9MHz IF output from that is an an LNA, then a Band Pass filter then the Airspy is connected to the BPF via it's ADC1 port.

It's fairly simple.  Un-check the "Frequency Check" box in the exp EXTIO and set the global offset in HDSDR so that it's on the correct freq, and that's all there is to it.

I have several LNA's the one I'm using at the moment is this: http://lna4hf.blogspot.com/

I just wanted to provide some feed back on this new feature you've added to the EXTIO.  It seems to work just fine.  I'd recommend adding it to the main branch.  I'm sure others would be interested in trying it.  I'll report more feedback as I use this new setup.  For now I'm very happy to be able to dispose of the upconverter I've been using (at least to set it aside).  

The reason I wanted to use this setup as I am now is that I use a GPSDO to clock the Airspy.  It's VERY Accurate with no noticable drift.  However, there IS minor drift in upconverter.  Just enough to be noticable, but not really that bad.  I wanted to see if I could do this so I could remove the upconverter.  And NOW I CAN.

So thank you VERY MUCH!
