### ISSUE TITLE
Airspy Decimation during Recording

### ISSUE THREAD

**Issue by benjamingrogg** [IW0HDV/extio-iw0hdv#10]
Dear Andrea

Many thanks for the Airspy ExtIO which works great on my Airspy Mini / Spyverter.
As far I know Airspy Mini have a fixed Sample Rate (3MHz and 6MHz).
Because of performance issues I use always 3MHz which works very well on my PC.
But when I Record (RF) it is too much for my Disk (SDCard). 
In SDRSharp I can set the Sample rate and the Decimation. Is there a way to implement this in the Airspy ExtIO or is there an option for that to set the Decimation also for recording?

Many thanks for any hint,
Benny

**Comment by amontefusco** [comment]
ExtIO doesn't provide DSP functions; it is up to the calling SDR program (SDR#, HDSDR, GQRX) to provide such feature.
