### ISSUE TITLE
Using Airspy with an IF setting

### ISSUE THREAD

**Issue by bill-orange** [IW0HDV/extio-iw0hdv#12]
I would like to use Airspy with with a microwave receiver and LNA.  The IF is about 10Ghz.  When I input the IF frequency in HDSRD I get the error message EXTIO

"ExtIO-DLL don't accept IF-Frequency"

Is there a way around this?  Am I doing something wrong?  It works just fine off an antenna.

Bill

**Comment by amontefusco** [comment]
Hi Bill,

I think that message is due to some misconfiguration on Options->RF Front end panel.

**Comment by bill-orange** [comment]
Thanks!  Please note that that I corrected my post. The IF is 10Ghz not 10Mhz. I screwed up counting my zeros. I was able to get the system to work using AirSpy’s software which is not as nice as HDSDR. I would rather use HDSDR with your DLL if possible.  The system doesn’t do much in the house. The local beacon is at 368Mhz which certainly won’t make it through my walls.

**Comment by amontefusco** [comment]
Bill,

In which part of HDSDR are you operating when you attempt to setup the downconverter offset Frequency ?

**Comment by amontefusco** [comment]
If you provide me, in private, further details about your setup, I can try to provide on that issue.
Or you can try to ask help on HDSDR mailing list.

**Comment by bill-orange** [comment]
I will take you up on your generous offer, but it will be a few days before I will send over the information.  I am still working out the details on my setup and I don't want to ask you do do this twice.  I have had some success so far  Using AirSpy's software, I can waive the feed horn around the room. The backgound noise changes with the temperature of the walls.  Progress.
