### ISSUE TITLE
Spurs/images/ghost traces seen

### ISSUE THREAD

**Issue by BWhit69** [IW0HDV/extio-iw0hdv#13]
I am using a pair of Airspy HF+ Discoveries and HDSDR to record the MW band thanks to your great ExtIO.  While using HDSDR version 280B11 and your ExtIO version 1.0.8 last week in Grayland, Washington I noted several instances of ghost traces on the waterfall screen where there shouldn't be any.  A Perseus running at the same time did not show these and neither did SDR#.

I'm wondering if you know what might cause this?

If you want some IQ files showing the problem I'd be happy to send them or give you a link to download them.

Thanks.  Bill Whitacre

**Comment by amontefusco** [comment]
Did you try the very same Airspy HF+ and pc/antenna setup with SDR# instead of HDSDR ?

**Comment by BWhit69** [comment]
Yes and there were no problems using SDR#.

I tried two different HF+ Discoveries and they both showed the same problems using HDSDR.

---

**Comment by amontefusco** [comment]
Which release of ExtIO are you using and which firmware ?

If you terminate the antenna input on 50 ohm, are you seeing thst spurious signals whatever the rx freq is ?

In case you are using the last release of extio, please give a try with the previous one.

**Comment by BWhit69** [comment]
HF+ Discovery with firmware R3.0.6-BB and your ExtIO v. 1.0.8-2-1404.

---

**Comment by amontefusco** [comment]
You should test with the last release of DLL.

**Comment by amontefusco** [comment]
With the last DLL and HDSDR 2.77 I am unable to see spurious signals,  firmware R3.0.6-BB.

**Comment by BWhit69** [comment]
OK, I’ll try that combination and let you know.

---

**Comment by amontefusco** [comment]
So, are that the spurious signals?

![image](https://user-images.githubusercontent.com/244977/75385329-d6a04380-58df-11ea-9861-de6edc630aef.png)

Now I can see them terminating with 50-ohm load both inputs, irrespective of the dll and HDSDR release I'm using.

**Comment by BWhit69** [comment]
The spurs come and go - I assume with signal strength of the mixing signals.

They are visible on the screenshot below on non-10kHz and non-9kHz spacings.

658, 677, 678, 695, 698, 704, 708, 718, 758, 767, 768 should NOT have signals.  They do not show up on Perseus recording made at the same time and they do not show up on SDR# live listening.

**Comment by amontefusco** [comment]
However I can see them even on SDR #

![image](https://user-images.githubusercontent.com/244977/75386546-2bdd5480-58e2-11ea-8397-e23baa41df22.png)

**Comment by amontefusco** [comment]
However in my installation them show up even with SDR#

![image](https://user-images.githubusercontent.com/244977/75386604-46173280-58e2-11ea-9d01-210872554a8e.png)

**Comment by BWhit69** [comment]
Do you see any on MW?

I have not seen this before with this same set-up.

The situation was during maximum signal strengths of both domestic U.S. stations and TP signals from Asia from Grayland, Washington on a DKAZ antenna with lots of signal strength.

---

**Comment by amontefusco** [comment]
![image](https://user-images.githubusercontent.com/244977/75387077-1288d800-58e3-11ea-8661-f2739e59b221.png)

That is with SDR# and 50 ohm, but really doesn't change even removing the load.

**Comment by amontefusco** [comment]
> 
> Do you see any on MW? I have not seen this before with this same set-up. The situation was during maximum signal strengths of both domestic U.S. stations and TP signals from Asia from Grayland, Washington on a DKAZ antenna with lots of signal strength.

I'm in urban area with a lot of very strong FM local signals, put aside Vatican Radio.

**Comment by amontefusco** [comment]
The pattern changes using lower sample rate.

**Comment by amontefusco** [comment]
Same on W10 laptop not connected to the power grid.

**Comment by amontefusco** [comment]
really, it seems a low level of spurs is expected, see 

https://www.rtl-sdr.com/wp-content/uploads/2019/08/Spurious.pdf
