### ISSUE TITLE
Support of AirSpy new feature airspy_get_samplerates()

### ISSUE THREAD

**Issue by bvernoux** [IW0HDV/extio-iw0hdv#3]
Support of AirSpy new feature airspy_get_samplerates():
- See example of usage of airspy_get_samplerates() 
  https://github.com/airspy/host/blob/master/airspy-tools/src/airspy_rx.c#L788
- See example of usage of airspy_set_samplerate()
  https://github.com/airspy/host/blob/master/airspy-tools/src/airspy_rx.c#L836

This new feature requires requires at least [AirSpy Library V1.0.5](https://github.com/airspy/host/releases/tag/v1.0.5) or more and [AirSpy firmware v1.0.0-rc4](https://github.com/airspy/firmware/releases/tag/v1.0.0-rc4) or more.

**Comment by amontefusco** [comment]
Hi Benjamin,
I'm currently traveling for business, I'll give a look to the changes needed next weekend.

**Comment by bvernoux** [comment]
Thanks there is no hurry, if you have any problem or question ask me

**Comment by amontefusco** [comment]
Hi Benjamin,
I created the libairspy-1.0.6 branch that uses airspy_get_samplerates() in order to dynamically get the sample rates available.
However I see that the sample rates are still just two.

**Comment by bvernoux** [comment]
It can be any is it is dynamic now and you can even have custom firmware which list 20 or more sample rates.

**Comment by amontefusco** [comment]
> > It can be any is it is dynamic now and you can even have custom firmware which list 20 or more sample rates.

Good to know, I missed them.
Are available for download somewhere ?

**Comment by amontefusco** [comment]
BTW, how low does the sample rate get down ?

**Comment by bvernoux** [comment]
Officialy firmware for AirSpy NOS R2 support only 10MSPS & 2.5MSPS (minimum is 2.4MSPS)
Custom non official version support 6, 4, 3 & 2.5MSPS
