### ISSUE TITLE
SDRUno Needs 0.96 MSPS

### ISSUE THREAD

**Issue by BT-Justice** [IW0HDV/extio-iw0hdv#4]
Any chance of an updated Airspy ExtIO.dll which supports 0.96 MSPS for use with SDRUno?  SDRUno presently supports no higher MSPS rates using ExtIO.dll files.

**Comment by amontefusco** [comment]
Is 0.96 msps a rate  natively found in libairspy lib ?

**Comment by BT-Justice** [comment]
I do not know about libairspy or how the ExtIO.dll files are made.  I was mainly wondering if it was even an option to have a MSPS that low for your Airspy ExtIO.dll file.  The SDRUno software looks neat and I'd like to try it on shortwave.  The SDRPlay folks say there will not be support for higher MSPS rates using ExtIO.dll which was why I asked here.  And thanks by the way for making an ExtIO.dll for Airspy as I do like to play with HDSDR on shortwave from time to time :)

**Comment by amontefusco** [comment]
Ok, I understand now, sorry for misinterpretation of your message.

I am afraid that the minimum sample rate is still 2.5 MS/s, but I will double check what the latest releases of firmware for AirSpy and AirSpyMini are offering.

In any case, my airspy.dll last release reads dynamically from the hardware all the sample rates values available, so, when some new sample rates are made available, it should be just  a matter of refresh firmware into AirSpy hardware.

**Comment by BT-Justice** [comment]
Alright.  Thanks.

**Comment by amontefusco** [comment]
The current firmware release supports the following sample rates:
- 10MSPS & experimental 2.5MSPS for AirSpy NOS R0/R2
- 6MSPS & 3MSPS for AirSpy Mini

https://github.com/airspy/firmware/releases/tag/v1.0.0-rc9
