### ISSUE TITLE
ppm adjustment

### ISSUE THREAD

**Issue by BillDunn** [IW0HDV/extio-iw0hdv#5]
Would it be possible to add a ppm adjustment to the Airspy extio? When using some front ends such as HDSDR with a spyverter attached you can't use the front end calibration of HDSDR with a upconverter offset entered and the only way to approximate it is by altering the offset which still varies depending on what frequency is being used.

Thanks so much for your support of the Airspy extio.
Wm Dunn

**Comment by amontefusco** [comment]
How should be this adjustment implemented ? Is an offset on the frequency that dll receive  enough ?
Please elaborate a little bit.

**Comment by BillDunn** [comment]
Using the upconverter offset only adjust frequency correction at a specific frequency. ppm or parts per million adjust the frequency over a larger frequency range. Take a look at the usb extio for the rtl-sdr on the HDSDR site as an example. http://www.hdsdr.de/hardware.html  
Thx,
Wm Dunn

**Comment by BillDunn** [comment]
One other note on the use of PPM. This enables the user to open the extio and make changes to the ppm while watching the waterfall\spectrum and adjusting while watching the frequency shift to the calibration frequency such as wwv or chu.

**Comment by amontefusco** [comment]
Implemented in https://github.com/IW0HDV/extio-iw0hdv/commit/e4cd3f1dc5a132e707fa4d02076312b7eab9aef9
