### ISSUE TITLE
Airspy Mini support ?

### ISSUE THREAD

**Issue by zanco** [IW0HDV/extio-iw0hdv#7]
Hi, Airspy Mini runs with this extio but is off frequency and audio sample rate

Is it possible to have settings for the samplerates 3000000 and 6000000 so the Airspy Mini can also work with for example HDSDR ?

Thanks,
Ben

**Comment by amontefusco** [comment]
It should be possible to use even AirSpy, I bought an AirSpy mini in order to do that and released the 1.0.5 past November.
If you are able to compile the code yourself just extract the last master branch and it should work.

**Comment by zanco** [comment]
Thanks for your reply, but I would have no clue how to compile for Windows . 

Would you happen to have a link to a compiled version for me ?

**Comment by amontefusco** [comment]
The airspy dll with Airspy mini support has been added.

https://github.com/amontefusco/extio-iw0hdv/releases/download/v1.0.5/extio_airspy_cmake_mgw-v1.0.5.dll
