### ISSUE TITLE
Bit Packing in Airspy Extio

### ISSUE THREAD

**Issue by JMoore15** [IW0HDV/extio-iw0hdv#8]
Hi Andrea,

Would it be possible for you to add support for the bit packing feature in the Airspy Extio? It would really help with stuttering issues that I've been having in HDSDR. If you can, it would be much appreciated.

Best Regards,
Josh

**Comment by amontefusco** [comment]
Are you sure this is feasible?
It seems that the packed stream is just a REAL samples stream, not the I/Q that ExtIO needs.

**Comment by JMoore15** [comment]
I don't know all that much about the underlying technology, but it would be nice to have. However, if the ExtIO can't process real samples, it may not be doable.

**Comment by amontefusco** [comment]
Looking into the code in libairspy, it seems that packed mode is providing only real data.
So that would be pointless for Extio, which requires an I/Q complex stream, just because all SDR software need that. Extio is "merely" a plugin intended to present an abstraction layer to SDR software.
