### ISSUE TITLE
A bit of help and advice for EXTIO programming

### ISSUE THREAD

**Issue by tomb18** [IW0HDV/extio-iw0hdv#9]
Hi Andrea,
I am a C# programmer that is new to programming for EXTIO dll's. I have tried your latest extio for the AirSpy HF+ and it seems to work fine except for some reason, the device stops using the callback after 10 to 20 seconds.  There are no errors or anything.  I'm sure this is related to my inexperience.  I am using the EXTIO class released into the public domain by Youssef with my own DSP code although at the moment, I am not doing any DSP, just collecting IQ packets.
Do you have any idea what might be happening to cause it to stop with no errors or anything?
It just never does the callback after a while.
In general though I am not having much luck with the extio interface other than with your dll.  For example, Icom just released a extio dll for the IC-7610, and an Init works fine, but it will never execute a StartHW without an access violation when it does perfectly with your DLL.
Sorry for these newbie questions but I do not know where else to turn.
Here is the airspy log if this helps.  Thanks, Tom

[AIRSPYHF-IW0HDV-1.log](https://github.com/IW0HDV/extio-iw0hdv/files/2417721/AIRSPYHF-IW0HDV-1.log)

**Comment by amontefusco** [comment]
I think it is the first time someone, outside the inner magic circle of SDR software of whom I  am not part of, is attempting to use my ExtIO DLL, so, we are in uncharted territory.
Nonetheless, it should work as is.  
My suggestion is to do a test run using HDSDR, saving the log file.
Next, run your software and compare the two logs: the calls to the ExtIO API should appear in the same order.
 Moreover, I'll provide you with a special release with more debugging in the reception loop, in order to check if the reception thread is blocking.

Or you can compile it by yourself, of course.

**Comment by amontefusco** [comment]
Debug release found here:

https://github.com/IW0HDV/extio-iw0hdv/releases/tag/v1.0.8-2-ge3eb1d4

This is my test run with the debug release:


open:168 - Current directory: [C:\Users\andrew\HDSDR_270]
DllMain:113 - Compiled with MinGW, module handle: 6FCC0000
DllMain:114 - git sha1: e3eb1d4842e1ee1b33c31b099551ce116ac32c9b built on:  - Oct  1 2018, 21:55:26 - 

InitHW:64 - Instance #1 Dll: 6FD94020
Gui:43 - ********************************* pImpl: 0032A628 Gui addr: 074A2488
Gui:46 - xxxxxxxxxxxxxxxxxxx GetMyHandle: 6FCC0000
CtrlBoxDlgProcOnInit:103 - 074a2488
CtrlBoxDlgProcOnInit:105 - ********************************* Gui addr: 074A2488
AirSpyHfRadio:50 - device name: []
AirSpyHfRadio:54 - airspyhf_lib_version: 1.3.0
scan_devices:67 - # of device(s): 1
scan_devices:76 - device #0: 36524EAA22BF34E0
SetCallback:134 - Instance #1
OpenHW:72 - Instance #1
open:146 - airspyhf_open(): serial len: 0
open:162 - airspyhf_open(): generic open: 0
get_calibration:327 - airspyhf_get_calibration: (7)
open:174 - sample rates available: (1)
open:181 - samplerate(0): 768000
Hide:110 - xxxxxxxxxxxxxxxxxx GUI HIDE
~Gui:67 - ********************************* GUI destructor: Gui addr: 0032A628
Gui:43 - ********************************* pImpl: 074A4BC0 Gui addr: 0032BDC8
Gui:46 - xxxxxxxxxxxxxxxxxxx GetMyHandle: 6FCC0000
CtrlBoxDlgProcOnCommand:76 - 00000000
CtrlBoxDlgProcOnCommand:76 - 00000000
CtrlBoxDlgProcOnInit:103 - 0032bdc8
CtrlBoxDlgProcOnInit:105 - ********************************* Gui addr: 0032BDC8
OnInit:49 - Event ref: 00110548
OnInit:55 - ******* AirSpyHfCtrlGui: pImpl: 074A4BC0 Gui addr: 0032BDC8 Cfg: 0032D160, (AIRSPYHF36524EAA22BF34E0)
OnInit:66 - 0: 768000
OnInit:82 - Sample rate from cfg(0032D160): 768000
OnInit:99 - Calibration from cfg(0032D160): 7
get_calibration:327 - airspyhf_get_calibration: (7)
OnInit:114 - Calibration from radio: 7
CtrlBoxDlgProcOnCommand:76 - 0032BDC8
OkPressed:335 - event.id: 40001 item [7] selected in PPB edit
set_calibration:339 - airspyhf_set_calibration: (7)
CtrlBoxDlgProcOnCommand:76 - 0032BDC8
set_attenuator:398 - airspyhf_set_hf_attenuator: 0(0)
RefreshHfControls:252 - AirSpyHfCtrlGui::RefreshHfControls
Show:93 - xxxxxxxxxxxxxxxxxx GUI Show: move to x= 2110 y= 1214
GetHWSR:126 - Instance #1
get_sample_rate:251 - airspyhf_get_samplerate: (768000)
GetHWSR:225 - returned sr: 768000
SetHWLO:110 - Instance #1 freq: 103989983
StartHW:80 - Instance #1 LOfreq: 103989983
StartHW:160 - EXTIO_NS: 8192  EXTIO_BASE_TYPE_SIZE: 4 N:2
DisableControls:239 - AirSpyHfCtrlGui::DisableControls
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
SetHWLO:110 - Instance #1 freq: 103990531
SetHWLO:110 - Instance #1 freq: 103991079
SetHWLO:110 - Instance #1 freq: 103992175
SetHWLO:110 - Instance #1 freq: 103993819
SetHWLO:110 - Instance #1 freq: 103996011
SetHWLO:110 - Instance #1 freq: 103997655
SetHWLO:110 - Instance #1 freq: 104000944
SetHWLO:110 - Instance #1 freq: 104003136
SetHWLO:110 - Instance #1 freq: 104005328
SetHWLO:110 - Instance #1 freq: 104007520
SetHWLO:110 - Instance #1 freq: 104010260
SetHWLO:110 - Instance #1 freq: 104012452
SetHWLO:110 - Instance #1 freq: 104014644
SetHWLO:110 - Instance #1 freq: 104016836
SetHWLO:110 - Instance #1 freq: 104019028
SetHWLO:110 - Instance #1 freq: 104021220
SetHWLO:110 - Instance #1 freq: 104023960
SetHWLO:110 - Instance #1 freq: 104026152
SetHWLO:110 - Instance #1 freq: 104027796
SetHWLO:110 - Instance #1 freq: 104029440
SetHWLO:110 - Instance #1 freq: 104031632
SetHWLO:110 - Instance #1 freq: 104033824
SetHWLO:110 - Instance #1 freq: 104036564
SetHWLO:110 - Instance #1 freq: 104038756
SetHWLO:110 - Instance #1 freq: 104040948
SetHWLO:110 - Instance #1 freq: 104043140
SetHWLO:110 - Instance #1 freq: 104046429
SetHWLO:110 - Instance #1 freq: 104049718
SetHWLO:110 - Instance #1 freq: 104054103
SetHWLO:110 - Instance #1 freq: 104057392
SetHWLO:110 - Instance #1 freq: 104061229
SetHWLO:110 - Instance #1 freq: 104065614
SetHWLO:110 - Instance #1 freq: 104068903
SetHWLO:110 - Instance #1 freq: 104072192
SetHWLO:110 - Instance #1 freq: 104076029
SetHWLO:110 - Instance #1 freq: 104078221
SetHWLO:110 - Instance #1 freq: 104082058
SetHWLO:110 - Instance #1 freq: 104085347
SetHWLO:110 - Instance #1 freq: 104088636
SetHWLO:110 - Instance #1 freq: 104091925
SetHWLO:110 - Instance #1 freq: 104094665
SetHWLO:110 - Instance #1 freq: 104099050
SetHWLO:110 - Instance #1 freq: 104103435
SetHWLO:110 - Instance #1 freq: 104107272
SetHWLO:110 - Instance #1 freq: 104111657
SetHWLO:110 - Instance #1 freq: 104116042
SetHWLO:110 - Instance #1 freq: 104119879
SetHWLO:110 - Instance #1 freq: 104125360
SetHWLO:110 - Instance #1 freq: 104130841
SetHWLO:110 - Instance #1 freq: 104136870
SetHWLO:110 - Instance #1 freq: 104143996
SetHWLO:110 - Instance #1 freq: 104151122
SetHWLO:110 - Instance #1 freq: 104157700
SetHWLO:110 - Instance #1 freq: 104163729
SetHWLO:110 - Instance #1 freq: 104169758
SetHWLO:110 - Instance #1 freq: 104175239
SetHWLO:110 - Instance #1 freq: 104179076
SetHWLO:110 - Instance #1 freq: 104183461
SetHWLO:110 - Instance #1 freq: 104188942
SetHWLO:110 - Instance #1 freq: 104194971
SetHWLO:110 - Instance #1 freq: 104202645
SetHWLO:110 - Instance #1 freq: 104211415
SetHWLO:110 - Instance #1 freq: 104219637
SetHWLO:110 - Instance #1 freq: 104226763
SetHWLO:110 - Instance #1 freq: 104234985
SetHWLO:110 - Instance #1 freq: 104242659
SetHWLO:110 - Instance #1 freq: 104248688
SetHWLO:110 - Instance #1 freq: 104255266
SetHWLO:110 - Instance #1 freq: 104260199
SetHWLO:110 - Instance #1 freq: 104264584
SetHWLO:110 - Instance #1 freq: 104268421
SetHWLO:110 - Instance #1 freq: 104272806
SetHWLO:110 - Instance #1 freq: 104277191
SetHWLO:110 - Instance #1 freq: 104281028
SetHWLO:110 - Instance #1 freq: 104285413
SetHWLO:110 - Instance #1 freq: 104289250
SetHWLO:110 - Instance #1 freq: 104293635
SetHWLO:110 - Instance #1 freq: 104296924
SetHWLO:110 - Instance #1 freq: 104301309
SetHWLO:110 - Instance #1 freq: 104305694
SetHWLO:110 - Instance #1 freq: 104308983
SetHWLO:110 - Instance #1 freq: 104312272
SetHWLO:110 - Instance #1 freq: 104314464
SetHWLO:110 - Instance #1 freq: 104317204
SetHWLO:110 - Instance #1 freq: 104318848
SetHWLO:110 - Instance #1 freq: 104320492
SetHWLO:110 - Instance #1 freq: 104322136
SetHWLO:110 - Instance #1 freq: 104323780
SetHWLO:110 - Instance #1 freq: 104325972
SetHWLO:110 - Instance #1 freq: 104328164
SetHWLO:110 - Instance #1 freq: 104331453
SetHWLO:110 - Instance #1 freq: 104335838
SetHWLO:110 - Instance #1 freq: 104340223
SetHWLO:110 - Instance #1 freq: 104344060
SetHWLO:110 - Instance #1 freq: 104348445
SetHWLO:110 - Instance #1 freq: 104351734
SetHWLO:110 - Instance #1 freq: 104355023
SetHWLO:110 - Instance #1 freq: 104357215
SetHWLO:110 - Instance #1 freq: 104359955
SetHWLO:110 - Instance #1 freq: 104361599
SetHWLO:110 - Instance #1 freq: 104363243
SetHWLO:110 - Instance #1 freq: 104364887
SetHWLO:110 - Instance #1 freq: 104365435
SetHWLO:110 - Instance #1 freq: 104366531
SetHWLO:110 - Instance #1 freq: 104367079
SetHWLO:110 - Instance #1 freq: 104367627
SetHWLO:110 - Instance #1 freq: 104368175
SetHWLO:110 - Instance #1 freq: 104368723
SetHWLO:110 - Instance #1 freq: 104369271
SetHWLO:110 - Instance #1 freq: 104370915
SetHWLO:110 - Instance #1 freq: 104372559
SetHWLO:110 - Instance #1 freq: 104374203
SetHWLO:110 - Instance #1 freq: 104375847
SetHWLO:110 - Instance #1 freq: 104377491
SetHWLO:110 - Instance #1 freq: 104378587
SetHWLO:110 - Instance #1 freq: 104379135
SetHWLO:110 - Instance #1 freq: 104379683
SetHWLO:110 - Instance #1 freq: 104380231
SetHWLO:110 - Instance #1 freq: 104382971
SetHWLO:110 - Instance #1 freq: 104389000
SetHWLO:110 - Instance #1 freq: 104393933
SetHWLO:110 - Instance #1 freq: 104400511
SetHWLO:110 - Instance #1 freq: 104407637
SetHWLO:110 - Instance #1 freq: 104414763
SetHWLO:110 - Instance #1 freq: 104421341
SetHWLO:110 - Instance #1 freq: 104427370
SetHWLO:110 - Instance #1 freq: 104432851
SetHWLO:110 - Instance #1 freq: 104437236
SetHWLO:110 - Instance #1 freq: 104442169
SetHWLO:110 - Instance #1 freq: 104446554
SetHWLO:110 - Instance #1 freq: 104450939
SetHWLO:110 - Instance #1 freq: 104454228
SetHWLO:110 - Instance #1 freq: 104457517
SetHWLO:110 - Instance #1 freq: 104461902
SetHWLO:110 - Instance #1 freq: 104466287
SetHWLO:110 - Instance #1 freq: 104470124
SetHWLO:110 - Instance #1 freq: 104474509
SetHWLO:110 - Instance #1 freq: 104478894
SetHWLO:110 - Instance #1 freq: 104483279
SetHWLO:110 - Instance #1 freq: 104486568
SetHWLO:110 - Instance #1 freq: 104490953
SetHWLO:110 - Instance #1 freq: 104494242
SetHWLO:110 - Instance #1 freq: 104498627
SetHWLO:110 - Instance #1 freq: 104501916
SetHWLO:110 - Instance #1 freq: 104504108
SetHWLO:110 - Instance #1 freq: 104506848
SetHWLO:110 - Instance #1 freq: 104508492
SetHWLO:110 - Instance #1 freq: 104510136
SetHWLO:110 - Instance #1 freq: 104511780
SetHWLO:110 - Instance #1 freq: 104512876
SetHWLO:110 - Instance #1 freq: 104513424
SetHWLO:110 - Instance #1 freq: 104515068
SetHWLO:110 - Instance #1 freq: 104516164
SetHWLO:110 - Instance #1 freq: 104516712
SetHWLO:110 - Instance #1 freq: 104517260
SetHWLO:110 - Instance #1 freq: 104517808
SetHWLO:110 - Instance #1 freq: 104518356
SetHWLO:110 - Instance #1 freq: 104518904
SetHWLO:110 - Instance #1 freq: 104520000
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
SetHWLO:110 - Instance #1 freq: 104520548
SetHWLO:110 - Instance #1 freq: 104521096
SetHWLO:110 - Instance #1 freq: 104522192
SetHWLO:110 - Instance #1 freq: 104523836
SetHWLO:110 - Instance #1 freq: 104526028
SetHWLO:110 - Instance #1 freq: 104529317
SetHWLO:110 - Instance #1 freq: 104533702
SetHWLO:110 - Instance #1 freq: 104537539
SetHWLO:110 - Instance #1 freq: 104543020
SetHWLO:110 - Instance #1 freq: 104549049
SetHWLO:110 - Instance #1 freq: 104556175
SetHWLO:110 - Instance #1 freq: 104563849
SetHWLO:110 - Instance #1 freq: 104570975
SetHWLO:110 - Instance #1 freq: 104578101
SetHWLO:110 - Instance #1 freq: 104586323
SetHWLO:110 - Instance #1 freq: 104593997
SetHWLO:110 - Instance #1 freq: 104600575
SetHWLO:110 - Instance #1 freq: 104606604
SetHWLO:110 - Instance #1 freq: 104613182
SetHWLO:110 - Instance #1 freq: 104620308
SetHWLO:110 - Instance #1 freq: 104626337
SetHWLO:110 - Instance #1 freq: 104634559
SetHWLO:110 - Instance #1 freq: 104643878
SetHWLO:110 - Instance #1 freq: 104654293
SetHWLO:110 - Instance #1 freq: 104665256
SetHWLO:110 - Instance #1 freq: 104675671
SetHWLO:110 - Instance #1 freq: 104686634
SetHWLO:110 - Instance #1 freq: 104698145
SetHWLO:110 - Instance #1 freq: 104707464
SetHWLO:110 - Instance #1 freq: 104713493
SetHWLO:110 - Instance #1 freq: 104720071
SetHWLO:110 - Instance #1 freq: 104725004
SetHWLO:110 - Instance #1 freq: 104731582
SetHWLO:110 - Instance #1 freq: 104735967
SetHWLO:110 - Instance #1 freq: 104739804
SetHWLO:110 - Instance #1 freq: 104745285
SetHWLO:110 - Instance #1 freq: 104749122
SetHWLO:110 - Instance #1 freq: 104755700
SetHWLO:110 - Instance #1 freq: 104761729
SetHWLO:110 - Instance #1 freq: 104767758
SetHWLO:110 - Instance #1 freq: 104774884
SetHWLO:110 - Instance #1 freq: 104782010
SetHWLO:110 - Instance #1 freq: 104789136
SetHWLO:110 - Instance #1 freq: 104796262
SetHWLO:110 - Instance #1 freq: 104803936
SetHWLO:110 - Instance #1 freq: 104811062
SetHWLO:110 - Instance #1 freq: 104818188
SetHWLO:110 - Instance #1 freq: 104825314
SetHWLO:110 - Instance #1 freq: 104831343
SetHWLO:110 - Instance #1 freq: 104837921
SetHWLO:110 - Instance #1 freq: 104843950
SetHWLO:110 - Instance #1 freq: 104849431
SetHWLO:110 - Instance #1 freq: 104854912
SetHWLO:110 - Instance #1 freq: 104858749
SetHWLO:110 - Instance #1 freq: 104863134
SetHWLO:110 - Instance #1 freq: 104867519
SetHWLO:110 - Instance #1 freq: 104871904
SetHWLO:110 - Instance #1 freq: 104876289
SetHWLO:110 - Instance #1 freq: 104882318
SetHWLO:110 - Instance #1 freq: 104887251
SetHWLO:110 - Instance #1 freq: 104893829
SetHWLO:110 - Instance #1 freq: 104900955
SetHWLO:110 - Instance #1 freq: 104906984
SetHWLO:110 - Instance #1 freq: 104914110
SetHWLO:110 - Instance #1 freq: 104920139
SetHWLO:110 - Instance #1 freq: 104927265
SetHWLO:110 - Instance #1 freq: 104936035
SetHWLO:110 - Instance #1 freq: 104943161
SetHWLO:110 - Instance #1 freq: 104949190
SetHWLO:110 - Instance #1 freq: 104954123
SetHWLO:110 - Instance #1 freq: 104958508
SetHWLO:110 - Instance #1 freq: 104962893
SetHWLO:110 - Instance #1 freq: 104965085
SetHWLO:110 - Instance #1 freq: 104968374
SetHWLO:110 - Instance #1 freq: 104971663
SetHWLO:110 - Instance #1 freq: 104975500
SetHWLO:110 - Instance #1 freq: 104978789
SetHWLO:110 - Instance #1 freq: 104983174
SetHWLO:110 - Instance #1 freq: 104987559
SetHWLO:110 - Instance #1 freq: 104990848
SetHWLO:110 - Instance #1 freq: 104993040
SetHWLO:110 - Instance #1 freq: 104994684
SetHWLO:110 - Instance #1 freq: 104995780
SetHWLO:110 - Instance #1 freq: 104996328
SetHWLO:110 - Instance #1 freq: 104996876
SetHWLO:110 - Instance #1 freq: 104997424
SetHWLO:110 - Instance #1 freq: 104997972
SetHWLO:110 - Instance #1 freq: 104998520
SetHWLO:110 - Instance #1 freq: 104999616
SetHWLO:110 - Instance #1 freq: 105000712
SetHWLO:110 - Instance #1 freq: 105001260
SetHWLO:110 - Instance #1 freq: 105002356
SetHWLO:110 - Instance #1 freq: 105003452
SetHWLO:110 - Instance #1 freq: 105004000
SetHWLO:110 - Instance #1 freq: 105004548
SetHWLO:110 - Instance #1 freq: 105005096
SetHWLO:110 - Instance #1 freq: 105005644
SetHWLO:110 - Instance #1 freq: 105006192
SetHWLO:110 - Instance #1 freq: 105006740
SetHWLO:110 - Instance #1 freq: 105007288
SetHWLO:110 - Instance #1 freq: 105007836
SetHWLO:110 - Instance #1 freq: 105008932
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
SetHWLO:110 - Instance #1 freq: 105010028
SetHWLO:110 - Instance #1 freq: 105011672
SetHWLO:110 - Instance #1 freq: 105013864
SetHWLO:110 - Instance #1 freq: 105017153
SetHWLO:110 - Instance #1 freq: 105021538
SetHWLO:110 - Instance #1 freq: 105025375
SetHWLO:110 - Instance #1 freq: 105029760
SetHWLO:110 - Instance #1 freq: 105035241
SetHWLO:110 - Instance #1 freq: 105039078
SetHWLO:110 - Instance #1 freq: 105043463
SetHWLO:110 - Instance #1 freq: 105048944
SetHWLO:110 - Instance #1 freq: 105052781
SetHWLO:110 - Instance #1 freq: 105056070
SetHWLO:110 - Instance #1 freq: 105059359
SetHWLO:110 - Instance #1 freq: 105061551
SetHWLO:110 - Instance #1 freq: 105063743
SetHWLO:110 - Instance #1 freq: 105065935
SetHWLO:110 - Instance #1 freq: 105068127
SetHWLO:110 - Instance #1 freq: 105069771
SetHWLO:110 - Instance #1 freq: 105073608
SetHWLO:110 - Instance #1 freq: 105076897
SetHWLO:110 - Instance #1 freq: 105081282
SetHWLO:110 - Instance #1 freq: 105084022
SetHWLO:110 - Instance #1 freq: 105088407
SetHWLO:110 - Instance #1 freq: 105092792
SetHWLO:110 - Instance #1 freq: 105096081
SetHWLO:110 - Instance #1 freq: 105101014
SetHWLO:110 - Instance #1 freq: 105105399
SetHWLO:110 - Instance #1 freq: 105111428
SetHWLO:110 - Instance #1 freq: 105117457
SetHWLO:110 - Instance #1 freq: 105122938
SetHWLO:110 - Instance #1 freq: 105128967
SetHWLO:110 - Instance #1 freq: 105135545
SetHWLO:110 - Instance #1 freq: 105141574
SetHWLO:110 - Instance #1 freq: 105147603
SetHWLO:110 - Instance #1 freq: 105154729
SetHWLO:110 - Instance #1 freq: 105162403
SetHWLO:110 - Instance #1 freq: 105169529
SetHWLO:110 - Instance #1 freq: 105177751
SetHWLO:110 - Instance #1 freq: 105185973
SetHWLO:110 - Instance #1 freq: 105193099
SetHWLO:110 - Instance #1 freq: 105201321
SetHWLO:110 - Instance #1 freq: 105208447
SetHWLO:110 - Instance #1 freq: 105216121
SetHWLO:110 - Instance #1 freq: 105222150
SetHWLO:110 - Instance #1 freq: 105227631
SetHWLO:110 - Instance #1 freq: 105233660
SetHWLO:110 - Instance #1 freq: 105238045
SetHWLO:110 - Instance #1 freq: 105242430
SetHWLO:110 - Instance #1 freq: 105246815
SetHWLO:110 - Instance #1 freq: 105250104
SetHWLO:110 - Instance #1 freq: 105252296
SetHWLO:110 - Instance #1 freq: 105255585
SetHWLO:110 - Instance #1 freq: 105259422
SetHWLO:110 - Instance #1 freq: 105263807
SetHWLO:110 - Instance #1 freq: 105268192
SetHWLO:110 - Instance #1 freq: 105272577
SetHWLO:110 - Instance #1 freq: 105277510
SetHWLO:110 - Instance #1 freq: 105282991
SetHWLO:110 - Instance #1 freq: 105286828
SetHWLO:110 - Instance #1 freq: 105291213
SetHWLO:110 - Instance #1 freq: 105296694
SetHWLO:110 - Instance #1 freq: 105302175
SetHWLO:110 - Instance #1 freq: 105308204
SetHWLO:110 - Instance #1 freq: 105314233
SetHWLO:110 - Instance #1 freq: 105319714
SetHWLO:110 - Instance #1 freq: 105324099
SetHWLO:110 - Instance #1 freq: 105327936
SetHWLO:110 - Instance #1 freq: 105332321
SetHWLO:110 - Instance #1 freq: 105335610
SetHWLO:110 - Instance #1 freq: 105338899
SetHWLO:110 - Instance #1 freq: 105342188
SetHWLO:110 - Instance #1 freq: 105344928
SetHWLO:110 - Instance #1 freq: 105347668
SetHWLO:110 - Instance #1 freq: 105350408
SetHWLO:110 - Instance #1 freq: 105353148
SetHWLO:110 - Instance #1 freq: 105355340
SetHWLO:110 - Instance #1 freq: 105356984
SetHWLO:110 - Instance #1 freq: 105359176
SetHWLO:110 - Instance #1 freq: 105363561
SetHWLO:110 - Instance #1 freq: 105366301
SetHWLO:110 - Instance #1 freq: 105368493
SetHWLO:110 - Instance #1 freq: 105371782
SetHWLO:110 - Instance #1 freq: 105373974
SetHWLO:110 - Instance #1 freq: 105376166
SetHWLO:110 - Instance #1 freq: 105378906
SetHWLO:110 - Instance #1 freq: 105381098
SetHWLO:110 - Instance #1 freq: 105384935
SetHWLO:110 - Instance #1 freq: 105388772
SetHWLO:110 - Instance #1 freq: 105393157
SetHWLO:110 - Instance #1 freq: 105397542
SetHWLO:110 - Instance #1 freq: 105400282
SetHWLO:110 - Instance #1 freq: 105403022
SetHWLO:110 - Instance #1 freq: 105405214
SetHWLO:110 - Instance #1 freq: 105407406
SetHWLO:110 - Instance #1 freq: 105409598
SetHWLO:110 - Instance #1 freq: 105411790
SetHWLO:110 - Instance #1 freq: 105414530
SetHWLO:110 - Instance #1 freq: 105416722
SetHWLO:110 - Instance #1 freq: 105418914
SetHWLO:110 - Instance #1 freq: 105420558
SetHWLO:110 - Instance #1 freq: 105422202
SetHWLO:110 - Instance #1 freq: 105423846
SetHWLO:110 - Instance #1 freq: 105425490
SetHWLO:110 - Instance #1 freq: 105427134
SetHWLO:110 - Instance #1 freq: 105428778
SetHWLO:110 - Instance #1 freq: 105430422
SetHWLO:110 - Instance #1 freq: 105432066
SetHWLO:110 - Instance #1 freq: 105433162
SetHWLO:110 - Instance #1 freq: 105434258
SetHWLO:110 - Instance #1 freq: 105434806
SetHWLO:110 - Instance #1 freq: 105435354
SetHWLO:110 - Instance #1 freq: 105435902
SetHWLO:110 - Instance #1 freq: 105436450
SetHWLO:110 - Instance #1 freq: 105436998
SetHWLO:110 - Instance #1 freq: 105437546
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
send_iq_from_rx_to_dsp:72 - ---------- buflen: 8192
StopHW:96 - Instance #1
StopHW:174 - Stopping async data acquisition...
EnableControls:226 - AirSpyHfCtrlGui::EnableControls
CloseHW:143 - 1Instance #1 0032D2A0 00000000 0032BDC8
CloseHW:146 - 2Instance #1 0032D2A0 00000000 0032BDC8
~Gui:67 - ********************************* GUI destructor: Gui addr: 074A4BC0
CloseHW:149 - 3Instance #1 0032D2A0 00000000 00000000
~ExtioAirSpyHfRadio:62 - ~ExtioAirSpyHfRadio()
~AirSpyHfRadio:106 - ~AirSpyHfRadio
DllMain:130 - DLL_PROCESS_DETACH: BEFORE
DllMain:132 - DLL_PROCESS_DETACH: AFTER
